name: Publish release

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer

jobs:
  release:
    runs-on: macos-13

    steps:

    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.release.tag_name }}

    - name: Bootstrap
      uses: ./.github/actions/bootstrap

    - name: Publish to Carthage
      run: bundle exec Scripts/publish-to-carthage $(Scripts/version show-current)
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
